@startuml
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define primary_key(x) <b><u>x</u></b>
hide methods
hide stereotypes

' entities
Table(user, "user") {
    primary_key(id_user) INTEGER
    email VARCHAR[255]
}

Table(login, "login") {
    primary_key(login_id) INTEGER
    username VARCHAR[32]
    password VARCHAR[64]
    role VARCHAR[255]
    last_login DATETIME
    FK id_user
}

Table(album, "album\n(Album of players)") {
    primary_key(id_album) INTEGER
}

Table(player, "player") {
    primary_key(id_player) INTEGER
    name VARCHAR[32]
    lastname VARCHAR[32]
    position VARCHAR[2]
    age INTEGER
    goals INTEGER
    FK id_team
}

Table(coach, "coach") {
    primary_key(id_coach) INTEGER
    name VARCHAR[32]
    lastname VARCHAR[32]
    FK id_team
}

Table(team, "team") {
    primary_key(id_team) INTEGER
    name VARCHAR[32]
    shield VARCHAR[255]
}

' relationships
user "1" --> "1" album
user "1" --> "1..N" login

album "1..N" --> "1..N" player

team "1" --> "1..N" player
team "1" --> "1..N" coach
@enduml