@startuml

left to right direction

actor "User" as User
actor "Administrator" as Admin

rectangle "Admin Possibilities" {
    Admin --> (Add player)
    Admin --> (Edit player)
    Admin --> (Discharge player)
    Admin --> (Add Coach)
    Admin --> (Edit Coach)
    Admin --> (Discharge Coach)
    Admin --> (See users)
}

rectangle "Database interaction" {
    User --> (See Players)
    User --> (See Teams)
}

rectangle "Interactive Part" {
    User --> (Open pack)
    User --> (Discard repeated player)
    User --> (See Album)
}

rectangle "Session" {
    User --> (Login)
    User --> (Logout)
    User --> (Register)
}

@enduml